# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-ubuntu"
      vb.cpus = 2
      vb.memory = "4096"
  end

  config.vm.synced_folder "data/", "/data"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
  SHELL

  config.vm.provision "docker" do |d|
    d.run "rancher", image: "rancher/server", args: "-d -v /data/rancher/mysql:/var/lib/mysql -v /data/rancher/cattle:/var/lib/cattle --restart=always -p 8080:8080"
  end

  config.vm.provision "shell", inline: <<-SHELL
    if [ $(grep -c 'tcp://0.0.0.0:2376' /etc/default/docker) -eq "0" ]
    then
      echo 'DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock ${DOCKER_OPTS}"' >> /etc/default/docker
    fi
  SHELL

end
