# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-ubuntu"
    vb.cpus = 2  
    vb.memory = "4096"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
  SHELL
  
  config.vm.provision "docker" do |d|
  
  end
  
end